assets={
	primitives:["plane","box","sphere","disc","cylinder","cone","torus"],
	skyboxes:["desert","dusk","hilly","rain","TropicalSunnyDay"],
	structures:["farm_barn_01","farm_silo_01","tipi","huts","coffin","fences"],
	vegetations:["farm_tree_01","farm_stump_01","farm_rocks_01","tree1"],
	characters:["Joan","Vincent"],
	vehicles:["farm_tractor_01"],
	sounds:["door.mp3","forest-ambient.ogg","nature-ambiance.ogg","soft-forest-music.ogg","tractor.wav","hello.mp3","old_door.ogg"]
}